### ISSUE TITLE
Check if crates compile on their own

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3730]
If one tries to run `FEDIMINT_BUILD_FORCE_GIT_HASH=1 cargo install fedimint-cli --version 0.2.0-rc2` then it errors with:

```
error[E0433]: failed to resolve: could not find `Builder` in `task`
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fedimint-core-0.2.0-rc2/src/task.rs:408:26
    |
408 |             tokio::task::Builder::new()
    |                          ^^^^^^^ could not find `Builder` in `task`
    |
help: consider importing one of these items
    |
399 +     use bitcoin30::script::Builder;
    |
399 +     use bitcoin::blockdata::script::Builder;
    |
399 +     use std::thread::Builder;
    |
399 +     use tokio::runtime::Builder;
    |
help: if you import `Builder`, refer to it directly
    |
408 -             tokio::task::Builder::new()
408 +             Builder::new()
    |

error[E0433]: failed to resolve: could not find `Builder` in `task`
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fedimint-core-0.2.0-rc2/src/task.rs:420:26
    |
420 |             tokio::task::Builder::new()
    |                          ^^^^^^^ could not find `Builder` in `task`
    |
help: consider importing one of these items
    |
399 +     use bitcoin30::script::Builder;
    |
399 +     use bitcoin::blockdata::script::Builder;
    |
399 +     use std::thread::Builder;
    |
399 +     use tokio::runtime::Builder;
    |
help: if you import `Builder`, refer to it directly
    |
420 -             tokio::task::Builder::new()
420 +             Builder::new()
    |
```

This is likely caused by missing feature flags in `Cargo.toml` that get masked by feature unification on the workspace level otherwise. We need to check all published crates for such failures.

The `FEDIMINT_BUILD_FORCE_GIT_HASH=1` environment variable is necessary till #3727 is fixed.

**Comment by elsirion** [comment]
Turns out this is not about *features*, but *rustflags*, in particular `--cfg tokio_unstable`. I don't see a good way of setting this from inside the published crate, the easiest workaround I could come up with is setting `RUSTFLAGS="--cfg tokio_unstable"`.

@dpc do you have any other ideas? Otherwise I'd close as wontfix.
