### ISSUE TITLE
CI job to compile each crate separately

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2255]
Was just trying to run `cargo check -p fedimint-bin-tests` by itself and it wouldn't compile. Would be nice if CI enforced that packages like this could compile on their own.

```
error[E0433]: failed to resolve: could not find `bitcoincore_rpc` in `fedimint_bitcoind`
  --> fedimint-bin-tests/src/main.rs:48:47
   |
48 |         let (host, auth) = fedimint_bitcoind::bitcoincore_rpc::from_url_to_url_auth(&url)?;
   |                                               ^^^^^^^^^^^^^^^ could not find `bitcoincore_rpc` in `fedimint_bitcoind`

error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> fedimint-bin-tests/src/main.rs:48:14
   |
48 |         let (host, auth) = fedimint_bitcoind::bitcoincore_rpc::from_url_to_url_auth(&url)?;
   |              ^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `str`
   = note: all local variables must have a statically known size
   = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> fedimint-bin-tests/src/main.rs:48:28
   |
48 |         let (host, auth) = fedimint_bitcoind::bitcoincore_rpc::from_url_to_url_auth(&url)?;
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
```
